config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :campaigns
  resources :chapters
  resources :characters
  resources :events
  resources :profiles
  match "profiles/:old_id/switch_to/:new_id",
    to: "profiles#switch_active_profile",
    as: :switch_active_profile,
    via: [:put, :post, :get]

  # Defines the root path route ("/")
  root "profiles#show"
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :bigint           not null, primary key
#  description :string
#  end_date    :date
#  name        :string
#  start_date  :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  chapter_id  :bigint           not null
#
# Indexes
#
#  index_events_on_chapter_id  (chapter_id)
#
# Foreign Keys
#
#  fk_rails_...  (chapter_id => chapters.id)
#
class Event < ApplicationRecord
  resourcify

  belongs_to :chapter
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: "Event was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: "Event was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :description, :chapter_id)
  end
end

app/views/events/_breadcrumbs.html.erb
<% if current_user.is_chapter_staff_or_greater? %>
  <div>
    <%= button_to edit_event_path(event), { class: "btn btn-primary", disabled: !policy(event).edit? } do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
        <title>Edit event <%= event.name %></title>
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
      </svg>
      Edit event
    <% end %>
  </div>
<% end %>
<%# Check the EventPolicy#index? method, which is inherited from ApplicationPolicy#index? %>
<% if policy(event).index? %>
  <div>
    <%= link_to "Back to events", events_path %>
  </div>
<% end %>
<% if policy(event).destroy? %>
  <div>
    <%= button_to "Destroy this event", event, method: :delete %>
  </div>
<% end %>

app/views/events/_events.html.erb
<div id="events">
  <% events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :chapter_id, style: "display: block" %>
    <%= form.select :chapter_id, chapters, selected: event.chapter_id, include_blank: "Select a hosting chapter" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_table.html.erb
<table class="table table-hover">
<thead>
  <tr>
    <% if current_user.is_chapter_staff_or_greater? %>
    <th></th>
    <% end %>
    <th>Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Chapter</th>
  </tr>
</thead>
<tbody>
  <% events.each do |event| %>
    <tr>
      <% if current_user.is_chapter_staff_or_greater? %>
      <td>
        <%= button_to edit_event_path(event), { class: "btn btn-primary", disabled: !policy(event).edit? } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <title>Edit event <%= event.name %></title>
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
        <% end %>
      </td>
      <% end %>
      <td>
        <%= link_to event.name, event_path(event) %>
      </td>
      <td>
        <%= l(event.start_date) %>
      </td>
      <td>
        <%= l(event.end_date) %>
      </td>
      <td>
        <%= link_to event.chapter.name, chapter_path(event.chapter) %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event, chapters: @chapters %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<%= render "events", events: @events %>

<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event, chapters: @chapters %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<div id="<%= dom_id @event %>">
  <p>
    <strong>Start date:</strong>
    <%= @event.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @event.end_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Chapter:</strong>
    <%= link_to @event.chapter.name, chapter_path(@event.chapter) %>
  </p>
</div>

<%= render "breadcrumbs", event: @event %>