config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :campaigns
  resources :chapters
  resources :characters
  resources :events
  resources :profiles
  match "profiles/:old_id/switch_to/:new_id",
    to: "profiles#switch_active_profile",
    as: :switch_active_profile,
    via: [:put, :post, :get]

  # Defines the root path route ("/")
  root "profiles#show"
end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  profile_id :bigint           not null
#  user_id    :bigint
#
# Indexes
#
#  index_characters_on_profile_id  (profile_id)
#  index_characters_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (profile_id => profiles.id)
#  fk_rails_...  (user_id => users.id)
#
class Character < ApplicationRecord
  belongs_to :profile
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[show edit update destroy]

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character, notice: "Character was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @character.update(character_params)
      redirect_to @character, notice: "Character was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @characters = Character.all
  end

  def show
    @attributes = @character.attributes
  end

  def destroy
    @character.destroy
    redirect_to characters_url, notice: "Character was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_character
    @character = Character.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def character_params
    params.require(:character).permit(:name, :profile_id)
  end
end

app/views/characters/_breadcrumbs.html.erb
<br />

<% if policy(Character).new? && !current_page?(action: "new") %>
  <div>
    <%= link_to "New character", new_character_path %>
  </div>
<% end %>
<% if !current_page?(action: "index") %>
  <% if policy(character).index? || (character.new_record? && policy(character).new?) %>
    <div>
      <%= link_to "Back to characters", characters_path %>
    </div>
  <% end %>
  <% if !current_page?(action: "new") %>
    <% if policy(character).show? && !current_page?(action: "show") %>
      <div>
        <%= link_to "Show this character", @character %>
      </div>
    <% end %>
    <% if policy(character).edit? && !current_page?(action: "edit") %>
      <div>
        <%= button_to edit_character_path(character), { class: "btn btn-primary", method: :get } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <title>Edit character <%= character.name %></title>
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
          Edit character
        <% end %>
      </div>
    <% end %>
    <% if policy(character).destroy? %>
      <div>
        <%= button_to "Delete character", character, { class: "btn btn-primary", method: :delete } %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/characters/_characters.html.erb
<% if characters.present? %>
  <table class="table table-hover">
  <thead>
    <tr>
      <% characters.first.attributes.keys.each do |attrs| %>
        <th><%= attrs.titleize %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% characters.each do |character| %>
      <tr>
        <% character.attributes.values.each do |value| %>
          <td>
            <%= value %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  </table>
<% end %>

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :profile_id, style: "display: block" %>
    <%= form.text_field :profile_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Show this character", @character %> |
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/index.html.erb
<h1>Characters</h1>

<%= render "characters", characters: @characters %>

<%= link_to "New character", new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>

<table class="table table-hover">
<thead>
  <tr>
    <% @attributes.keys.each do |attrs| %>
      <th><%= attrs.titleize %></th>
    <% end %>
  </tr>
</thead>
<tbody>
  <tr>
    <% @attributes.values.each do |value| %>
      <td>
        <%= value %>
      </td>
    <% end %>
  </tr>
</tbody>
</table>

<div>
  <%= link_to "Edit this character", edit_character_path(@character) %> |
  <%= link_to "Back to characters", characters_path %>

  <%= button_to "Destroy this character", @character, method: :delete %>
</div>