config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :campaigns
  resources :chapters
  resources :characters
  resources :events
  resources :profiles
  match "profiles/:old_id/switch_to/:new_id",
    to: "profiles#switch_active_profile",
    as: :switch_active_profile,
    via: [:put, :post, :get]

  # Defines the root path route ("/")
  root "profiles#show"
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <%= link_to 'Chapters', chapters_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Events', events_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Campaigns', campaigns_path, class: 'nav-link' %>
                </li>
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to 'Characters', characters_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item dropdown">
                        <div class="btn-group">
                            <button type="button" class="btn btn-info">
                                <%= link_to current_user.active_profile.for_acting_as.titleize, profile_path(current_user.active_profile) %>
                            </button>
                            <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <%# <span class="sr-only">Toggle Dropdown</span> # TODO: "sr-only" class is not hiding this content; fix it! %>
                            </button>
                            <div class="dropdown-menu">
                                <h6 class="dropdown-header">Switch To</h6>
                                <% current_user.profiles.each do |profile| %>
                                    <% active_profile_id = current_user.active_profile.id %>
                                    <% disabled = active_profile_id == profile.id %>
                                    <%= link_to "#{profile.for_acting_as.titleize} Profile", switch_active_profile_path(old_id: active_profile_id, new_id: profile.id), method: :put, class: disabled ? "dropdown-item disabled" : "dropdown-item", disabled: disabled %>
                                <% end %>
                                <div class="dropdown-divider"></div>
                                <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
                                <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item btn btn-outline-primary' %>
                            </div>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LarpManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
      <%= render "layouts/nav" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>